dist: bionic

sudo: required

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

env:
  matrix:
    - DJANGO_VERSION=2.2.*
    - DJANGO_VERSION=3.0.*
    - DJANGO_VERSION=dev

stages:
  - lint
  - test
  - deploy

install:
  - pip install -e .[dev]
  - pip install codecov
  - if [[ $DJANGO_VERSION == dev ]]; then
    pip install -e git+https://github.com/django/django@master#egg=django;
    else
    pip install Django==$DJANGO_VERSION -U;
    fi

after_failure:
  - pip freeze

script:
  - coverage run ./manage.py test

after_success:
  - codecov

jobs:
  allow_failures:
    - env: DJANGO_VERSION=dev

  include:
    - stage: lint
      install:
        - pip install flake8
      before_script: skip
      before_install: skip
      script:
        - flake8 token_tools
      after_success: skip

    - stage: deploy
      install: skip
      before_script: skip
      before_install: skip
      script: skip
      deploy:
        skip_cleanup: true
        stage: deploy
        provider: pypi
        user: __token__
        password:
          secure: "cA2+4rjUNeYllXokqhO8XkTjfhXA7M42bQvue+cMISKfYZ2x75S3XyQ2ElXWx7+7Ik43cdV4oRFg6a8+8JZMob96IRFtKwY1KCe/asHmvQMx+kSrh+FkbqYcmCA7KXkKfSXw2X94tcBAD5IsfQFkq03MUDyZvV9liBvGC5WV4Da/Svzt0jQp2lWOCkjvVGHKdnoYKXvOrE55+y2L/JQtc8+eiBuJIjMbl9MaV7ga9IuCVXrPn+cACGtjoMZNLcZ9L7iumaoeJA3+SrzeJESnql5sCezQ0ii+yge1pa4JnlyKvNm4fAbkDFEc1JUlX0l4+EVTmaAqexrrv35Z4/pNtUZUr/Aia7zhGnlvhtnVRHRLUTWVjQp4btn8+SrrYZ/DAQPx5vxApRj/XsNlc/Q+xYVI0lCjX4ZKFUK7y6AWi7J6rPxw6YwOTqVe/zhRFnfuxwfAsg5s4a9G1QzRF6veKbTPqKGwxtEXNpt9S6Ixj02fTOP5rH9tBYORcOt2cVpn8by/aZXb70/zy4OqxE89JnLrid3oarXzBh92XK5boufxLbh2slxVe0yDOTe57FwLxRAvy4+4YWfAyAP7OL7NEhYrwkMpooY1uPouiwXI00h/figFMzZRobStaOqH1U0dxb2mR2Lr2wYdJonScPRqk3e41EYGLSq61mgfeGabtAw="
        on:
          tags: true
