# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install flake8

    - name: Lint with flake8
      run: |
        flake8 token_tools test_token_tools

  build:
    runs-on: ubuntu-20.04
    #TODO: Fix when github action do not show failed for the workflow with continue-on-error
    #continue-on-error: ${{ matrix.experimental }}
    needs: [lint]
    strategy:
      matrix:
        python-version: ['3.6', '3.9', '3.10']
        django-version: ['2.2.*', '3.2.*', '4.1.*']
        exclude:
          - python-version: '3.10'
            django-version: '2.2.*'
          - python-version: '3.6'
            django-version: '4.1.*'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install .[dev] -U
        if [[ ${{ matrix.django-version }} == dev ]]; then
          pip install -e git+https://github.com/django/django@main#egg=django;
        else
          pip install Django==${{ matrix.django-version }} -U;
        fi

    - name: Test with coverage
      run: |
        coverage run ./manage.py test

    - name: Coverage upload
      run: |
        pip install codecov
        codecov
